backend/urls.py
from django.urls import path
from backend import views

app_name = "backend"

urlpatterns = [
    path('',views.index,name='index'),
    path('about/', views.about, name='about'),
    path("post/",views.ListBlogPost.as_view(),name="posts"),
    path("post/<int:pk>/", views.detail_blog_post, name="post-detail"),
    path("post/<int:pk>/create-comment/", views.create_comment, name="create-comment"),
    path('term-conditions/', views.term_conditions, name='term-conditions'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('restaurant/', views.restaurant, name='restaurant'),
    path('team/', views.TeamMemberView.as_view(), name="team"),
    path("gallary/",views.hotel_room_gallery,name="gallery-hotel-room"),
    path("gallary/conference/", views.conference_gallery, name="gallery-Conference"),
    path("gallary/resort-reserve/", views.resort_reserve, name="Resort-Reserve"),
    path("gallary/weeding-hall/", views.weeding_hall, name="weeding-hall"),

]

hotel_reservation_django_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('backend.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(get_user_model(), related_name="posts"
                               , on_delete=models.CASCADE)
    title = models.CharField(max_length=60)
    image1 = models.ImageField(upload_to="./images/post/")
    image2 = models.ImageField(upload_to="./images/post/")
    upload_date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def get_absolute_url(self):
        return reverse('backend:post-detail', args=[self.id])


class Tag(models.Model):
    name = models.CharField(max_length=60)


class TagPost(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(get_user_model(), related_name="comments"
                               , on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
class RestaurantItem(models.Model):
    categories = (
        ("Breakfast", "Breakfast"),
        ("Lunch", "Lunch"),
        ("Dinner", "Dinner"),
        ("Drink", "Drink"),
    )
    title = models.CharField(max_length=30)
    desc = models.TextField()
    category = models.CharField(max_length=20, choices=categories)
    image = models.ImageField(upload_to='./images/food/')
    price = models.PositiveSmallIntegerField()


class TeamMember(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='./image/team/')
    position = models.CharField(max_length=30)
    instagram = models.CharField(max_length=60,null=True,default=None)
    twitter = models.CharField(max_length=60,null=True,default=None)
    facebook = models.CharField(max_length=60,null=True,default=None)
    pinterest = models.CharField(max_length=60,null=True,default=None)



class GalleryImage(models.Model):
    categories = (
        ("Hotel Room", "Hotel Room"),
        ("Conference", "Conference"),
        ("Resort Reserve", "Resort Reserve"),
        ("Weeding Hall", "Weeding Hall"),
    )
    image = models.ImageField(upload_to='./image/gallery/')
    category = models.CharField(max_length=20,choices=categories)

backend/views.py
from django.contrib import messages
from django.shortcuts import render
from backend import models
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.shortcuts import redirect

def index(request):
    recent_posts = models.Post.objects.order_by("upload_date").all()[0:2]

    context = {

        "recent_posts": recent_posts,
    }
    return render(request, 'backend/index.html', context)


def about(request):
    return render(request, 'backend/about.html', {})


def term_conditions(request):
    return render(request, 'backend/term-conditions.html', {})


def privacy_policy(request):
    return render(request, 'backend/privacy-policy.html', {})


def restaurant(requests):
    breakfast = models.RestaurantItem.objects.filter(category='Breakfast')
    lunch = models.RestaurantItem.objects.filter(category='Lunch')
    dinner = models.RestaurantItem.objects.filter(category='Dinner')
    drink = models.RestaurantItem.objects.filter(category='Drink')

    context = {
        "breakfast": breakfast,
        "lunch": lunch,
        "dinner": dinner,
        "drink": drink,

    }
    return render(requests, 'backend/restaurant.html', context)


class TeamMemberView(ListView):
    model = models.TeamMember
    paginate_by = 3
    template_name = 'backend/team.html'


def hotel_room_gallery(request):
    objects = models.GalleryImage.objects.filter(category="Hotel Room")
    context = {
        "objects": objects,
    }
    return render(request, 'backend/gallery.html', context)


def conference_gallery(request):
    objects = models.GalleryImage.objects.filter(category="Conference")
    context = {
        "objects": objects,
    }
    return render(request, 'backend/gallery.html', context)


def resort_reserve(request):
    objects = models.GalleryImage.objects.filter(category="Resort Reserve")
    context = {
        "objects": objects,
    }
    return render(request, 'backend/gallery.html', context)


def weeding_hall(request):
    objects = models.GalleryImage.objects.filter(category="Weeding Hall")
    context = {
        "objects": objects,
    }
    return render(request, 'backend/gallery.html', context)


class ListBlogPost(ListView):
    model = models.Post
    paginate_by = 3
    template_name = "backend/blog.html"


def detail_blog_post(request, pk):
    post = get_object_or_404(models.Post, id=pk)
    tags = models.TagPost.objects.filter(post=post)
    comments = models.Comment.objects.filter(post=post)
    recent_posts = models.Post.objects.order_by("upload_date").all()[0:3]

    context = {
        "post": post,
        "tags": tags,
        "comments": comments,
        "recent_posts": recent_posts,
    }
    return render(request, "backend/blog-detail.html", context)


@login_required
@require_POST
def create_comment(request,pk):
    post = get_object_or_404(models.Post, id=pk)
    user = request.user
    comment_is_exists = models.Comment.objects.filter(post=post,author=user)
    if comment_is_exists.exists():
        messages.error(request, "you can write only one comment")
        return redirect("backend:post-detail", pk=pk)

    text = request.POST['message']
    comment = models.Comment.objects.create(post=post,author=user,text=text)
    comment.save()
    messages.success(request, "success")

    return redirect("backend:post-detail",pk=pk)

templates/backend/blog-detail.html
{% extends 'base.html' %}
{% load static%}

{% block content %}
       <!-- Inner Banner -->
        <div class="inner-banner inner-bg3">
            <div class="container">
                <div class="inner-title">
                    <ul>
                        <li>
                            <a href="{% url 'backend:index' %}">Home</a>
                        </li>
                        <li><i class='bx bx-chevron-right'></i></li>
                        <li>Blog Details </li>
                    </ul>
                    <h3>Blog Details</h3>
                </div>
            </div>
        </div>
        <!-- Inner Banner End -->

        <!-- Blog Details Area -->
        <div class="blog-details-area pt-100 pb-70">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog-article">



                            <div class="blog-article-img">
                                <img src="{{ post.image1.url }}" alt="Images">
                            </div>

                            <div class="blog-article-title">
                                <h2>{{ post.title }}</h2>
                                <ul>

                                    <li>
                                        <i class='bx bx-user'></i>
                                        {{ post.author.name }}
                                    </li>

                                    <li>
                                        <i class='bx bx-calendar'></i>
                                        {{ post.upload_date }}
                                    </li>
                                </ul>
                            </div>

                            <div class="article-content">

                                <p>
                                   {{ post.text }}
                                </p>


                            </div>

                            <div class="another-content">
                                <div class="content-img">
                                    <img src="{{ post.image2.url }}" alt="Images">
                                </div>

                            </div>

                            <div class="comments-wrap">
								<h3 class="title">Comments</h3>
								<ul>

                                    {% for comment in comments %}
                                        <li>
										<h3>{{ comment.author.username }}</h3>
										<span>{{ comment.date}}</span>
										<p>
                                            {{ comment.text }}
                                        </p>
                                    </li>
                                    {% endfor %}




								</ul>
                            </div>
                            {% include 'include/message.html' %}

                            <div class="comments-form">
                                <div class="contact-form">
                                    <h2>Leave A Comment</h2>
                                    <form  action="{% url 'backend:create-comment' post.id %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12">
                                                <div class="form-group">
                                                    <textarea name="message" class="form-control" id="message" cols="30" rows="8" required data-error="Write your message" placeholder="Your Message"></textarea>
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-md-12">
                                                <button type="submit" class="default-btn btn-bg-three">
                                                    Post A Comment
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="side-bar-wrap">
                            <div class="search-widget">
                                <form class="search-form">
                                    <input type="search" class="form-control" placeholder="Search...">
                                    <button type="submit">
                                        <i class="bx bx-search"></i>
                                    </button>
                                </form>
                            </div>

                            <div class="side-bar-widget">
                                <h3 class="title">Recent Posts</h3>
                                <div class="widget-popular-post">

                                    {% for recent_post in recent_posts %}
                                         <article class="item">
                                        <a href="{{ recent_post.get_absolute_url }}" class="thumb">
                                            <span class="full-image cover bg1" role="img"></span>
                                        </a>
                                        <div class="info">
                                            <h4 class="title-text">
                                                <a href="{{ recent_post.get_absolute_url }}">
                                                    {{ recent_post.text|truncatechars:30 }}
                                                </a>
                                            </h4>
                                            <ul>
                                                <li>
                                                    <i class='bx bx-user'></i>
                                                    29K
                                                </li>
                                                <li>
                                                    <i class='bx bx-message-square-detail'></i>
                                                    15K
                                                </li>
                                            </ul>
                                        </div>
                                    </article>
                                    {% endfor %}





                                </div>
                            </div>

                            <div class="side-bar-widget">
                                <h3 class="title">Tags</h3>
                                <ul class="side-bar-widget-tag">

                                    {% for tag in tags %}
                                        <li><a href="#">{{ tag.tag.name }}</a></li>

                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Blog Details Area End -->


{% endblock %}

templates/backend/blog.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


      <!-- Blog Area -->
        <div class="blog-area pt-100 pb-70">
            <div class="container">
                <div class="section-title text-center">
                    <span class="sp-color">BLOGS</span>
                    <h2>Our Latest Blogs to the Intranational Journal at a Glance</h2>
                </div>
                <div class="row pt-45">

                    {% for post in post_list %}

                        <div class="col-lg-4 col-md-6">
                        <div class="blog-item">
                            <a href="{{ post.get_absolute_url }}">
                                <img src="{{ post.image1.url }}" alt="Images">
                            </a>
                            <div class="content">
                                <ul>
                                    <li>{{ post.upload_date }}</li>
                                    <li><i class='bx bx-user'></i>29K</li>
                                    <li><i class='bx bx-message-alt-dots'></i>15K</li>
                                </ul>
                                <h3>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </h3>
                                <p>{{ post.text|truncatechars:30 }}</p>
                                <a href="{{ post.get_absolute_url }}" class="read-btn">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>


                    {% endfor %}









                    <div class="col-lg-12 col-md-12">
                        <div class="pagination-area">
                            {% if page_obj.has_previous %}
                                <a href="{% url 'backend:posts'%}?page={{ page_obj.previous_page_number }}"
                                   class="prev page-numbers">
                                <i class='bx bx-chevrons-left'></i>
                            </a>
                            {% endif %}

                            {% for page_number in paginator.page_range %}
                                <a
                                        href="{% url 'backend:posts'%}?page={{ page_number }}"
                                        class="page-numbers {% if page_number == page_obj.number %}current{% endif %}"
                                >
                                    {{ page_number }}
                                </a>

                            {% endfor %}

                             {% if page_obj.has_next %}
                                <a href="{% url 'backend:posts'%}?page={{ page_obj.next_page_number }}"
                                   class="next page-numbers">
                                <i class='bx bx-chevrons-right'></i>
                            </a>
                            {% endif %}


                        </div>
                    </div>


                </div>
            </div>
        </div>
        <!-- Blog Area End -->


{% endblock %}

templates/backend/gallery.html
{% extends 'base.html' %}
{% load static%}

{% block content %}
     <div class="gallery-area pt-100 pb-70">
            <div class="container">
                <div class="tab gallery-tab">
                    <ul class="tabs text-center">
                        <li>
                            <a href="{% url 'backend:gallery-hotel-room' %}">Hotel Room</a>
                        </li>

                        <li>
                            <a href="{% url 'backend:gallery-Conference' %}">Conference</a>
                        </li>

                        <li>
                            <a href="{% url 'backend:Resort-Reserve' %}">Resort Reserve</a>
                        </li>

                        <li>
                            <a href="{% url 'backend:weeding-hall' %}">Weeding Hall</a>
                        </li>

                    </ul>


                       <div class="tab_content current active pt-45">
                        <div class="tabs_item current">
                            <div class="gallery-tab-item">
                                <div class="gallery-view">
                                    <div class="row">
                                        {% for object in objects %}
                                                 <div class="col-lg-4 col-sm-6">
                                            <div class="single-gallery">
                                                <img src="{{ object.image.url }}" alt="Images">
                                                <a href="{{ object.image.url }}" class="gallery-icon">
                                                    <i class='bx bx-plus'></i>
                                                </a>
                                            </div>
                                        </div>
                                        {% endfor %}





                                    </div>
                                </div>
                            </div>
                        </div>





                    </div>
                </div>
            </div>
        </div>


{% endblock %}

templates/backend/restaurant.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


        <!-- Breakfast Area -->
        <div class="breakfast-area pt-100 pb-70">
            <div class="container">
                <div class="section-title text-center">
                    <h2>Breakfast</h2>
                    <span> 8:00 AM - 12:00 PM</span>
                </div>
                <div class="row pt-45">

                    {% for br in breakfast %}
                        <div class="col-lg-6">
                        <div class="restaurant-item">
                            <div class="row align-items-center">
                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-img">
                                        <img src="{{ br.image.url }}" alt="Images">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-content">
                                        <h3><a href="#">{{ br.title }}</a></h3>
                                        <p>
                                            {{ br.desc }}
                                        </p>
                                        <h4>${{ br.price }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}



                </div>
            </div>
        </div>
        <!-- Breakfast Area End -->

        <!-- Lunch Area -->
        <div class="lunch-area pb-70">
            <div class="container">
                <div class="section-title text-center">
                    <h2>Lunch</h2>
                    <span> 12:30 PM - 3:00 PM</span>
                </div>
                {% for l in lunch %}

                <div class="row pt-45">
                    <div class="col-lg-6">
                        <div class="restaurant-item">
                            <div class="row align-items-center">
                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-img">
                                        <img src="{{ l.image.url }}" alt="Images">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-content">
                                        <h3><a href="#">{{ l.title }}</a></h3>
                                        <p>
                                            {{ l.desc }}
                                        </p>
                                        <h4>${{ l.price }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}




                </div>
            </div>
        </div>
        <!-- Lunch Area End -->

        <!-- Dinner Area -->
        <div class="dinner-area pb-70">
            <div class="container">
                <div class="section-title text-center">
                    <h2>Dinner</h2>
                    <span> 8:00 PM - 11:00 PM</span>
                </div>
                {% for d in dinner %}
                    <div class="row pt-45">
                    <div class="col-lg-6">
                        <div class="restaurant-item">
                            <div class="row align-items-center">
                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-img">
                                        <img src="{{ d.image.url }}" alt="Images">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-content">
                                        <h3><a href="#">{{ d.title }}</a></h3>
                                        <p>
                                            {{ d.desc }}
                                        </p>
                                        <h4>${{ d.price }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}






                </div>
            </div>
        </div>
        <!-- Dinner Area End -->

        <!-- Drink Area -->
        <div class="drink-area pb-70">
            <div class="container">
                <div class="section-title text-center">
                    <h2>Drink</h2>
                    <span> All Time</span>
                </div>

                {% for dr in drink %}
                         <div class="row pt-45">
                    <div class="col-lg-6">
                        <div class="restaurant-item">
                            <div class="row align-items-center">
                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-img">
                                        <img src="{{ dr.image.url }}" alt="Images">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 p-0">
                                    <div class="restaurant-content">
                                        <h3><a href="#">{{ dr.title }}</a></h3>
                                        <p>
                                            {{ dr.desc }}
                                        </p>
                                        <h4>${{ dr.price }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}






                </div>
            </div>
        </div>
        <!-- Drink Area End -->



{% endblock %}

templates/backend/team.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


        <!-- Team Style Area -->
        <div class="team-style-area pt-100 pb-70">
            <div class="container">
                <div class="section-title text-center">
                    <span class="sp-color">TEAM</span>
                    <h2>Let's Meet Up With Our Special Team Members</h2>
                </div>
                <div class="row pt-45">

                    {% for teammember in teammember_list %}
                          <div class="col-lg-4 col-md-6">
                        <div class="team-item">
                                <img src="{{ teammember.image.url }}" alt="Images">

                            <div class="content">
                                <h3>{{ teammember.name }}</h3>
                                <span>{{ teammember.position }}</span>
                                <ul class="social-link">
                                    <li>
                                        <a href="{{ teammember.facebook }}" target="_blank"><i class='bx bxl-facebook'></i></a>
                                    </li>
                                    <li>
                                        <a href="{{ teammember.twitter }}" target="_blank"><i class='bx bxl-twitter'></i></a>
                                    </li>
                                    <li>
                                        <a href="{{ teammember.instagram }}" target="_blank"><i class='bx bxl-instagram'></i></a>
                                    </li>
                                    <li>
                                        <a href="{{ teammember.pinterest }}" target="_blank"><i class='bx bxl-pinterest-alt'></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>



                    {% endfor %}










                    <div class="col-lg-12 col-md-12">
                        <div class="pagination-area">
                            {% if page_obj.has_previous %}
                                <a href="{% url 'backend:team'%}?page={{ page_obj.previous_page_number }}"
                                   class="prev page-numbers">
                                <i class='bx bx-chevrons-left'></i>
                            </a>
                            {% endif %}

                            {% for page_number in paginator.page_range %}
                                <a
                                        href="{% url 'backend:team'%}?page={{ page_number }}"
                                        class="page-numbers {% if page_number == page_obj.number %}current{% endif %}"
                                >
                                    {{ page_number }}
                                </a>

                            {% endfor %}

                             {% if page_obj.has_next %}
                                <a href="{% url 'backend:team'%}?page={{ page_obj.next_page_number }}"
                                   class="next page-numbers">
                                <i class='bx bx-chevrons-right'></i>
                            </a>
                            {% endif %}
                            



                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Team Style Area End -->
{% endblock %}

templates/include/message.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success" id="message">
      <button type="button" class="close" data-dismiss="alert" onclick="GFG_Fun()">
      ×
      </button>
      <strong>{{message}}</strong>
    </div>

      <script>
        let div = document.getElementById("message")

        function GFG_Fun() {
            div.remove();
        }
    </script>
 {% endfor %}
{% endif %}